main: AdvancedPGM\Main
api: [2.0.0]

name: AdvancedPGM
description: A world gamemode switch plugin.
version: 1.0.0
author: CaptainDuck
website: https://github.com/CaptainDuck/AdvancedPGM-PerWorldGamemode-

commands:
  apgm:
    description: Manage PerWorldGamemodes
    usage: "/apgm <gm>"
    permission: apgm.cmd
    aliases: [wgm]

permissions:
  apgm.cmd:
    default: op
    description: "Allow setting a per-world gamemode"
  apgm.cmd.exempt:
    default: false
    description: "Users with this permissions will ignore per world gm"

